version: '3'
services:

    symfony-mysql:
      container_name: symfony-mysql
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: symfony_docker
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      ports:
        - '4306:3306'
      volumes:
        - ./infrastructure/mysql:/var/lib/mysql
    
    php:
        container_name: php
        build:
            context: ./infrastructure/php
        ports:
            - '90:90'
        volumes:
            - ./app:/var/www/symfony_docker
        depends_on:
            - symfony-mysql
    
    symfony-nginx:
        container_name: symfony-nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./app:/var/www/symfony_docker
            - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - symfony-mysql
        links:
            - php
