version: '3'
services:

    symfony-mysql:
      container_name: symfony-mysql
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - ${MSQL_PORT}:3306
      volumes:
        - ./infrastructure/mysql:/var/lib/mysql
    
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./infrastructure/php/Dockerfile
            args:
                GIT_USER_NAME: ${GIT_USER_NAME}
                GIT_USER_SURNAME: ${GIT_USER_SURNAME}
                GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        ports:
            - '90:90'
        volumes:
            - ./app:/var/www/symfony_docker
        depends_on:
            - symfony-mysql
        environment:
            GIT_USER_NAME: desdeDockerCompose

    symfony-nginx:
        container_name: symfony-nginx
        image: nginx:stable-alpine
        ports:
            - ${SYMFONY_PORT}:80
        volumes:
            - ./app:/var/www/symfony_docker
            - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - symfony-mysql
        links:
            - php
