version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: msqlPasswd
      MYSQL_DATABASE: symfonyDb
      MYSQL_USER: mysqlUser
      MYSQL_PASSWORD: mysqlUserPasswd
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq-symfony
    image: rabbitmq
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=crabbitUser
      - RABBITMQ_DEFAULT_PASS=rabbitPasswd

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data: